#------------------------------------------------------------------------------
# ktune configuration file for sim2real system identification
#
# Testbed: Pendulum setup — see `Sysid_Testbed_Setup.xlsx` for physical parameters.
# Purpose: Used with ktune to drive and record trajectory for system identification.
#
# Notes for users:
#   - Units are SI (meters, kilograms, seconds, newtons, radians)
#---------------------------#---------------------------#---------------------------
# Testbed: Pendulum (see Pendulum_Testbed_Configurations.xlsx for details)
# Mass in kg
# Inertia in kg*m^2
# Length in meters
# Configuration
    # Disc_CD
    # Axle_A
    # Spacer_Set1 (BC/BD/CD)
    # Arm_A (100mm)
#---------------------------
sysid:
  # Hardware configuration
  actuator_id: 11
  motor_name: "sts3215v12"
  ip: "192.168.42.1"

  # Pendulum Params
  total_inertia: 0.009272826
  total_g_bias: -0.744369943
  length: 0.100
  mass: 0.74117693
  
  # Motor parameters
  error_gain: 0.16489
  winding_resistance: 1.0
  torque_constant: 1.0787
  
  # Test configuration
  repetitions: 4
  kp_values: [4, 8, 12, 16, 24, 32]
  trajectories: 
    - "lift_and_drop"
    - "sin_sin"
    - "up_and_down"
    - "sin_time_square"
    - "brutal"

 
